// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mgpg.proto

package MGpg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateKeyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Expiry               int64    `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Armor                bool     `protobuf:"varint,5,opt,name=armor,proto3" json:"armor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKeyRequest) Reset()         { *m = GenerateKeyRequest{} }
func (m *GenerateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyRequest) ProtoMessage()    {}
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae006496676238b6, []int{0}
}

func (m *GenerateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyRequest.Unmarshal(m, b)
}
func (m *GenerateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyRequest.Marshal(b, m, deterministic)
}
func (m *GenerateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyRequest.Merge(m, src)
}
func (m *GenerateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyRequest.Size(m)
}
func (m *GenerateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyRequest proto.InternalMessageInfo

func (m *GenerateKeyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GenerateKeyRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *GenerateKeyRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GenerateKeyRequest) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *GenerateKeyRequest) GetArmor() bool {
	if m != nil {
		return m.Armor
	}
	return false
}

type GenerateKeyReply struct {
	Pub                  []byte   `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	Sec                  []byte   `protobuf:"bytes,2,opt,name=sec,proto3" json:"sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKeyReply) Reset()         { *m = GenerateKeyReply{} }
func (m *GenerateKeyReply) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyReply) ProtoMessage()    {}
func (*GenerateKeyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae006496676238b6, []int{1}
}

func (m *GenerateKeyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyReply.Unmarshal(m, b)
}
func (m *GenerateKeyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyReply.Marshal(b, m, deterministic)
}
func (m *GenerateKeyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyReply.Merge(m, src)
}
func (m *GenerateKeyReply) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyReply.Size(m)
}
func (m *GenerateKeyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyReply proto.InternalMessageInfo

func (m *GenerateKeyReply) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *GenerateKeyReply) GetSec() []byte {
	if m != nil {
		return m.Sec
	}
	return nil
}

type GenerateKeyResponse struct {
	ErrorCode            int64             `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string            `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Response             *GenerateKeyReply `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenerateKeyResponse) Reset()         { *m = GenerateKeyResponse{} }
func (m *GenerateKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyResponse) ProtoMessage()    {}
func (*GenerateKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae006496676238b6, []int{2}
}

func (m *GenerateKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyResponse.Unmarshal(m, b)
}
func (m *GenerateKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyResponse.Marshal(b, m, deterministic)
}
func (m *GenerateKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyResponse.Merge(m, src)
}
func (m *GenerateKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyResponse.Size(m)
}
func (m *GenerateKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyResponse proto.InternalMessageInfo

func (m *GenerateKeyResponse) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GenerateKeyResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GenerateKeyResponse) GetResponse() *GenerateKeyReply {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*GenerateKeyRequest)(nil), "MGpg.GenerateKeyRequest")
	proto.RegisterType((*GenerateKeyReply)(nil), "MGpg.GenerateKeyReply")
	proto.RegisterType((*GenerateKeyResponse)(nil), "MGpg.GenerateKeyResponse")
}

func init() { proto.RegisterFile("mgpg.proto", fileDescriptor_ae006496676238b6) }

var fileDescriptor_ae006496676238b6 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x5d, 0xd3, 0xd6, 0x76, 0x1a, 0xa1, 0x8c, 0x52, 0x56, 0x41, 0x08, 0xf1, 0x92, 0x53,
	0x0e, 0x11, 0x7c, 0x01, 0x85, 0x1e, 0xb4, 0x97, 0x7d, 0x01, 0x49, 0xd3, 0x21, 0x14, 0xba, 0xd9,
	0x75, 0x37, 0x05, 0xf3, 0x02, 0xde, 0x7c, 0x67, 0xc9, 0x6c, 0x14, 0x2b, 0xbd, 0xcd, 0xf7, 0x9b,
	0x3f, 0x3b, 0xf3, 0x2d, 0x80, 0xae, 0x6d, 0x9d, 0x5b, 0x67, 0x5a, 0x83, 0xa3, 0xf5, 0xca, 0xd6,
	0xe9, 0xa7, 0x00, 0x5c, 0x51, 0x43, 0xae, 0x6c, 0xe9, 0x85, 0x3a, 0x45, 0xef, 0x07, 0xf2, 0x2d,
	0x22, 0x8c, 0x9a, 0x52, 0x93, 0x14, 0x89, 0xc8, 0x66, 0x8a, 0x63, 0x94, 0x70, 0x51, 0x19, 0xad,
	0xa9, 0x69, 0xe5, 0x39, 0xe3, 0x1f, 0x89, 0xd7, 0x30, 0x26, 0x5d, 0xee, 0xf6, 0x32, 0x62, 0x1e,
	0x04, 0x2e, 0x61, 0x42, 0x1f, 0x76, 0xe7, 0x3a, 0x39, 0x4a, 0x44, 0x16, 0xa9, 0x41, 0xf5, 0xd5,
	0xa5, 0xd3, 0xc6, 0xc9, 0x71, 0x22, 0xb2, 0xa9, 0x0a, 0x22, 0x7d, 0x84, 0xc5, 0xd1, 0x1e, 0x76,
	0xdf, 0xe1, 0x02, 0x22, 0x7b, 0xd8, 0xf0, 0x12, 0xb1, 0xea, 0xc3, 0x9e, 0x78, 0xaa, 0xf8, 0xfd,
	0x58, 0xf5, 0x61, 0xfa, 0x25, 0xe0, 0xea, 0xa8, 0xd1, 0x5b, 0xd3, 0x78, 0xc2, 0x3b, 0x00, 0x72,
	0xce, 0xb8, 0xb7, 0xca, 0x6c, 0xc3, 0x1d, 0x91, 0x9a, 0x31, 0x79, 0x32, 0x5b, 0xc2, 0x7b, 0xb8,
	0x0c, 0x69, 0x4d, 0xde, 0x97, 0x35, 0x0d, 0x27, 0xc5, 0x0c, 0xd7, 0x81, 0x61, 0x01, 0x53, 0x37,
	0xcc, 0xe3, 0xd3, 0xe6, 0xc5, 0x32, 0xef, 0x5d, 0xcb, 0xff, 0x6f, 0xaa, 0x7e, 0xeb, 0x8a, 0x57,
	0x60, 0x63, 0xf1, 0x19, 0xe6, 0x7f, 0xaa, 0x50, 0x9e, 0x68, 0x64, 0xab, 0x6f, 0x6f, 0x4e, 0x64,
	0xc2, 0xac, 0xf4, 0x6c, 0x33, 0xe1, 0xbf, 0x7a, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x17,
	0x96, 0x2f, 0xb9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MGpgClient is the client API for MGpg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MGpgClient interface {
	GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error)
}

type mGpgClient struct {
	cc *grpc.ClientConn
}

func NewMGpgClient(cc *grpc.ClientConn) MGpgClient {
	return &mGpgClient{cc}
}

func (c *mGpgClient) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error) {
	out := new(GenerateKeyResponse)
	err := c.cc.Invoke(ctx, "/MGpg.MGpg/GenerateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MGpgServer is the server API for MGpg service.
type MGpgServer interface {
	GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error)
}

// UnimplementedMGpgServer can be embedded to have forward compatible implementations.
type UnimplementedMGpgServer struct {
}

func (*UnimplementedMGpgServer) GenerateKey(ctx context.Context, req *GenerateKeyRequest) (*GenerateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKey not implemented")
}

func RegisterMGpgServer(s *grpc.Server, srv MGpgServer) {
	s.RegisterService(&_MGpg_serviceDesc, srv)
}

func _MGpg_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MGpgServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MGpg.MGpg/GenerateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MGpgServer).GenerateKey(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MGpg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MGpg.MGpg",
	HandlerType: (*MGpgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateKey",
			Handler:    _MGpg_GenerateKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mgpg.proto",
}
